AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template for creating IAM role to be used by CreateActivation as well as by instance profile for on-premises hosts managed by SSM

Parameters:

  SSMDocument:
    Type: String
    Description: SSM Document for forwarding SSM session logs to centralized s3 bucket
    Default: SSM-SessionManagerRunShell
  
  IAMRoleName:
    Type: String
    Description: IAM Role for SSM
    Default: Liveline-HybridActivationRole 

  KMSKeyArn:
    Type: String
    Description: Centralized Logging Account KMS Key Arn
    Default: arn:aws:kms:us-east-1:082494019291:key/7be77241-dbf3-4255-af88-a7ecba80debf

  S3BucketName:
    Type: String
    Description: Centralized Logging Account S3 Bucket Name
    Default: liveline-bucketdetailsss

Resources:

  # DOC: https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-create-iam-instance-profile.html#create-iam-instance-profile-ssn-logging
  HybridActivationRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Ref IAMRoleName
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - 'sts:AssumeRole'
        Path: /
        Policies:   
          - PolicyName: HybridActivationCustomInlinePolicies
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ssm:CreateActivation
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - iam:PassRole
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - cloudformation:DescribeStacks
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - ssm:UpdateDocument
                  Resource: 
                    !Sub 
                      - 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:document/${SSMDocName}'
                      - { SSMDocName: !Ref SSMDocument }
                - Effect: Allow
                  Action:
                    - kms:Decrypt
                    - kms:GenerateDataKey
                  Resource: !Ref KMSKeyArn
                - Effect: Allow
                  Action:
                    - ssmmessages:CreateControlChannel
                    - ssmmessages:CreateDataChannel
                    - ssmmessages:OpenControlChannel
                    - ssmmessages:OpenDataChannel
                    - ssm:UpdateInstanceInformation
                  Resource: "*"
                - Effect: Allow
                  Action: 
                    - s3:PutObject
                    - s3:PutObjectAcl
                  Resource: 
                    - !Sub arn:aws:s3:::${S3BucketName}/*
                - Effect: Allow
                  Action: 
                    - s3:GetEncryptionConfiguration
                  Resource: 
                    - !Sub arn:aws:s3:::${S3BucketName}
                # - Effect: Allow
                #   Action: 
                #     - logs:CreateLogStream
                #     - logs:PutLogEvents
                #   Resource: 
                #     - arn:aws:logs:us-east-1:367521952991:log-group:/aws/ssm/SessionManagerLogs:*
                    # - !Sub arn:aws:s3:::${S3BucketName}

Outputs:
  HybridActivationIAMRole:
    Description: IAM Role to be used by Hybrid Activation
    Value: !Ref HybridActivationRole
    Export:
      Name: "HybridActivationIAMRoleName"